### ISSUE TITLE
Загрузить приложение на github-pages или любой другой хостинг

### ISSUE THREAD

**Issue by disovi** [Lyashka/SPA-VK#1]
Согласно условиям задания требуется 

> 6. Залить рабочее приложение на [github-pages](https://pages.github.com/) или на любой другой хостинг - по своему усмотрению.

**Comment by Merz1ota** [comment]
Позабыл как-то про пункт №6 
Я залил проект на github pages. 
Ссылка на GitHub: https://github.com/Lyashka/SPA-VK
Ссылка на GitHub Pages: https://lyashka.github.io/SPA-VK/

**Comment by disovi** [comment]
![image](https://user-images.githubusercontent.com/705617/195824204-c44c5927-3e7a-46fe-bf8e-08b48bf5af20.png)
как добавлять пользователей ?

**Comment by Merz1ota** [comment]
После авторизации, по кнопке "Построить" делается запрос на сервер, после чего выводится список друзей.
Или вы имеете ввиду функция с формой добавления пользователя в друзья?

**Comment by disovi** [comment]
@Lyashka вы неправильно поняли задание.

> 1. Создать SPA, на базе Vue, **позволяющее интерактивно добавлять/удалять пользователей Вк в список по их имени фамилии (с автодополнением), числовому id или имени пользователя**

В список могут быть добавлены произвольные пользователи.

**Comment by Merz1ota** [comment]
Понял, спасибо.
Тогда переделаю

**Comment by Merz1ota** [comment]
@disovi  Добрый вечер Владислав.
Я доделал функционал ТЗ, работа со списком пользователей Вк.
Ссылка на github pages: https://lyashka.github.io/SPA-VK/
